version: 1.0.1
# Your avatar url
avatar: /img/avatar.png
favicon: /img/avatar.png

# If the blog placement location is not the root directory, you can resolve the static file path error problem by configuring this path
# For example, if the access address is yelog.org/blog, you need to configure it as blog_path: / blog for normal access.
blog_path: /

# Link icons are displayed in the same order as below
link:
  theme: color # Link style, color: colored icon white: black and white icon
  items:
    github: https://github.com/dalv0911
    facebook: https://www.facebook.com/da0911

########## Multi-author mode ############
author:
  on: false
  authors:
    author1: Da Le
##############################

# Article classification settings
category:
  num: true # Show Articles by Category
  sub: true # Turn on multi-level classification
  width:
    lg: 120 # 1468px<Screen width left classification width
    md: 100 # 1024px<Screen width <=1468px Classification width on the left
    sm: 100 # 426px<Screen width <=1024px Classification width on the left（ipad）
# Multi-level classification description：
# For example, if multiple menus are set in the article, the default is a multi-level menu, that is,：tool>hexo
# categories:
#   - Tools
#   - hexo

# Custom menu in bottom left corner
menu:
  about:  # 'About' button
    on: true # whether to show
    url: /about  # Jump link
    type: 1 # Jump type 1: Asynchronous jump within the station 2: Jump to the current page 3: Open a new tab page
  friend: # 'Friend' button
    on: false # whether to show
  menus: # The other menus added are written under menus, as follows: dynamic menu 1, dynamic menu 2, dynamic menu 3

# End of statement
article_txt: 

bottom_text: ©2016-2019 Da Le
# Customize site copyright information at the bottom of the page
# If not filled in, customize as © 2017 author (this author is configured in the hexo root directory _config.yml)

reward: false
# true enable reward

searchAll: true
# true enable full text search
# The following operations are required to enable this function:
# 1. Run npm install hexo-generator-search --save in the hexo root directory to install the plugin
# 2. Add the following to _config.xml in the hexo root directory
# search:
# path: search.xml
# field: post

copyright: true
# Copyright info. of post | 文末版权信息

word_count: false
# true enable word count
# To enable this feature, you need to install the plugin: run npm i hexo-wordcount --save in the hexo root directory

# No garlic website count setting
# http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  on: true
  site_visit: true
  page_visit: true

########## Custom style settings ##############
# Table of contents | Article Directory
toc:
  max_depth: 3  # 1 - 6 (h1-h6) Maximum number of levels in the directory

# Article list The style that the mouse moves up, use the default effect when it is empty
article_list:
  title: '#383636' # Article list title color
  datetime: '#5e5e5f' # Post date color
  hover:
    background: '#e2e0e0'  # Background color: provide several: '# c1bfc1' '# fbf4a8'
    color:     # text color provides several：'#ffffff'
# Note: Because the color contains #, use single quotes'

# Article list background image
article_bg_img:
  on: true # whether to open
  src: /img/left-menu-background.jpg
  opacity: 0.3 # background image transparency, range 0 to 1

# List style
list: thread
# normal: normal style
# thread: list has a wireframe

# Reference block style
blockquote: github
# github: Similar to GitHub's quick reference
# bracket: style similar to left and right braces

# table style
table: green_title
# Similar to github's table style when empty
# green green style
# green_title Cyan table style

# Home background image
index_bg_img:
# Background of other pages
other_bg_img:

# Click image to enlarge style
img_resize: default
# Optional values:
# default: default (simple enlargement written by yourself)
# photoSwipe: use photoSwipe plugin

# Code segment highlight style, markdown syntax `demo`
code:
  theme: dark-red
# Supported topics:
# dark-red: red text (default)
# github: github style (grey background, black text)

highlight:
  on: true
  lineNum: true
  theme: atom-light
# Code highlight theme, the effect can be viewed https://highlightjs.org/static/demo/
# sublime: Sublime highlight theme
# Supported topics:
# darcula: refer to the topic of darcula in idea
# atom-dark: refer to Atom's dark theme
# atom-light: Refer to Atom's light topic
# github: Reference GitHub version highlight theme
# github-gist: GitHub-Gist theme
# brown-paper: Kraft paper effect
# gruvbox-light: light theme for gruvbox
# gruvbox-dark: dark theme for gruvbox
# rainbow:
# railscasts:
# sunburst:
# kimbie-dark:
# kimbie-light:
# school-book: paper effect
# zenbum: oschina also choose this highlight theme

# MathJax Math formula support
mathjax:
  on: true # Whether to enable
  per_page: false # If only rendering a single page, set this option to false, add mathjax: true to the page

# Mermaid support
mermaid:
  on: false
  cdn: //cdn.jsdelivr.net/npm/mermaid@8.4.2/dist/mermaid.min.js
  #cdn: //cdnjs.cloudflare.com/ajax/libs/mermaid/8.3.1/mermaid.min.js
  options: # For more configuration information, please refer to https://mermaidjs.github.io/#/mermaidAPI
    theme: 'default'
    startOnLoad: true
    flowchart:
      useMaxWidth: false
      htmlLabels: true

##############################

# Links
friends: null

########## Comment settings #############
comment:
  on: false
  type: gitalk  # Comment system: gitalk, disqus, agent, gitment, note: when using, configure in the corresponding position below
  comment_count: true  # Show the number of comments under the article title
  preload_comment: false  # preload comment area
  ## false: Reload the comment module when clicking on an area such as a comment bar
  ## true: Load comment section when the page loads
# Configuration of each comment system ↓↓

disqus:
  shortname:
# disqus comment system, which was certified by GFW in September 2016 and cannot be used in mainland China.
# Get shortname: https://help.disqus.com/customer/en/portal/articles/466208-what-s-a-shortname-

gentie:
  product_key:
# NetEase cloud post comment system, https://gentie.163.com/
# After registration, enter the background management and get the code: copy the productKey in product_key.
# NetEase cloud post does not support querying the number of comments for the time being, so when it is enabled, turn off the number of comments and comment_count: false above.

gitalk:
  githubID: dalv0911
  repo: dalv0911.github.io
  ClientID:
  ClientSecret:
  adminUser: dalv0911
  distractionFreeMode: true
  language: vie
  perPage: 10
# gitalk: Third-party chat plugin made with github issue
# https://github.com/gitalk/gitalk
# Parameter introduction:
# githubID: github username
# repo: issue of which repository to use
# ClientID and ClientSecret will create OAuth application: https://github.com/settings/applications/new
# adminUser: must be a collaborator of the above repository (with write permission), use your own github username
# distractionFreeMode: full screen mask effect
# language: Language: Support: en / zh-CN / zh-TW
# perPage: Data size for each load, default 10, maximum 100


gitment:
  owner: dalv0911
  repo: dalv0911.github.io
  client_id:
  client_secret:
# gitment: Comment system via github issue
# Open source address: https://github.com/imsun/gitment
# Instructions for use :

##########CND设置#############
CDN:
  jquery: //cdn.bootcss.com/jquery/2.2.4/jquery.min.js
  jquery_cookie: //cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.min.js
  jquery_ui: //cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.min.js
  jquery_ui_css: //cdn.bootcss.com/jqueryui/1.12.1/jquery-ui.min.css
  highlight: //cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js
  pjax: //cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js
  animate: //cdn.bootcss.com/animate.css/3.5.2/animate.min.css
  font_awsome: //cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css
  nprogres_js: //cdn.bootcss.com/nprogress/0.2.0/nprogress.min.js
  mathjax: //cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
  photoswipe_js: //cdn.bootcss.com/photoswipe/4.1.2/photoswipe.min.js
  photoswipe_ui_js: //cdn.bootcss.com/photoswipe/4.1.2/photoswipe-ui-default.min.js
  photoswipe_css: //cdn.bootcss.com/photoswipe/4.1.2/photoswipe.min.css
  photoswipe_skin_css: //cdn.bootcss.com/photoswipe/4.1.2/default-skin/default-skin.min.css
